services:
  kali:
    build:
      context: .
      args:
        - USER_PASS=${USER_PASS}
    container_name: kali-lab
    volumes:
      - /home/heverz/docker_config/kali_docker/volume:/home/heverz
    stdin_open: true
    tty: true
    restart: unless-stopped
